# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5ugTjB7BSvLEFtQwm76hPsOroMsR_2b
"""

import os
from google.colab import userdata
from groq import Groq

# Fetch secret key from Colab environment
api_key = userdata.get('GROQ_API_KEY')
client = Groq(api_key=api_key)

# Completely different sample inputs: Cooking Scenarios
sample_ingredients = """
Ingredients: 2 large eggs, 1 cup whole milk, 1.5 cups all-purpose flour,
2 tbsp melted butter, pinch of salt, 1 tsp vanilla extract.
"""

sample_recipe_name = "Classic Homemade Crepes"

# Select a new test type
selected_output_type = "Nutritional Analysis"

PROMPTS = {
    "Nutritional Analysis": f"""You are a certified nutritionist.
Analyze the following ingredients for '{sample_recipe_name}'.
STRICT RULES:
1. Provide an estimated calorie count per serving (assume 4 servings).
2. Highlight potential allergens found in the ingredients.
3. Suggest 2 healthy substitutions to reduce fat or sugar.
{sample_ingredients}""",

    "Step-by-Step Simplified Recipe": f"""You are a professional chef.
Convert these ingredients into a simple 3-step cooking process.
STRICT RULES:
1. Tone: Encouraging and clear.
2. Only mention the ingredients provided.
3. Keep each step under 20 words.
RECIPE: {sample_recipe_name}
{sample_ingredients}"""
}

system_prompt = PROMPTS[selected_output_type]

# Test Model Call
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[{"role": "user", "content": system_prompt}],
    temperature=0.3
)

print(f"--- GENERATED OUTPUT: {selected_output_type} ---")
print(response.choices[0].message.content)